### ISSUE TITLE
Policy is unsigned and unofficial

### ISSUE THREAD

**Issue by kravciak** [kubewarden/persistentvolumeclaim-storageclass-policy#9]
Version: v0.1.0

![Screenshot from 2024-03-23 11-01-35](https://github.com/kubewarden/persistentvolumeclaim-storageclass-policy/assets/538604/31d54b83-2522-4283-8c5d-ed29f1921053)

**Comment by viccuad** [comment]
artifacthub now shows correct v0.1.1, and recognizes the signatures.
Opened https://github.com/artifacthub/hub/issues/3733 for official status.
